package com.dev.fido.bridge.core.storage.model

import com.dev.fido.bridge.core.security.CryptoUtils

/**
 * Represents a persistent caBLE v2 state-assisted transaction link between an authenticator (phone)
 * and a client platform (PC/browser) per CTAP 2.3 §11.5.2.
 *
 * Encapsulates necessary secret keys, routing tokens, and metadata required to re-establish
 * out-of-band hybrid tunnels without scanning a QR code on subsequent authentication requests.
 *
 * @property linkId 8-byte unique identifier generated by authenticator to index this link.
 * @property linkSecret 32-byte shared symmetric secret derived during initial QR pairing.
 * @property contactId Opaque push notification or relay registration token (e.g., FCM/ntfy ID).
 * @property authenticatorPublicKey 65-byte uncompressed EC P-256 public key identifying authenticator.
 * @property authenticatorName Human-readable device label displayed to client platform (e.g., "Pixel 8 Pro").
 * @property tunnelServerDomain Fully qualified domain name of tunnel server (e.g., "cable.ua5v.com").
 * @property createdAtTimestamp System epoch timestamp (ms) when this pairing record was established.
 */
data class LinkingRecord(
    val linkId: ByteArray,
    val linkSecret: ByteArray,
    val contactId: ByteArray,
    val authenticatorPublicKey: ByteArray,
    val authenticatorName: String,
    val tunnelServerDomain: String,
    val createdAtTimestamp: Long = System.currentTimeMillis()
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as LinkingRecord
        if (!linkId.contentEquals(other.linkId)) return false
        if (!linkSecret.contentEquals(other.linkSecret)) return false
        if (!contactId.contentEquals(other.contactId)) return false
        if (!authenticatorPublicKey.contentEquals(other.authenticatorPublicKey)) return false
        if (authenticatorName != other.authenticatorName) return false
        if (tunnelServerDomain != other.tunnelServerDomain) return false
        return createdAtTimestamp == other.createdAtTimestamp
    }

    override fun hashCode(): Int {
        var result = linkId.contentHashCode()
        result = 31 * result + linkSecret.contentHashCode()
        result = 31 * result + contactId.contentHashCode()
        result = 31 * result + authenticatorPublicKey.contentHashCode()
        result = 31 * result + authenticatorName.hashCode()
        result = 31 * result + tunnelServerDomain.hashCode()
        result = 31 * result + createdAtTimestamp.hashCode()
        return result
    }

    override fun toString(): String {
        return "LinkingRecord(" +
                "linkId=${CryptoUtils.encodeBase64UrlNoPadding(linkId)}, " +
                "authenticatorName='$authenticatorName', " +
                "domain='$tunnelServerDomain', " +
                "createdAt=$createdAtTimestamp)"
    }
}
